### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by juliecheng** [sssharkie1/gallant-grapes#16]
- [ ] MEDIUM swap derek and meredith's pick so that it's aligned
- [ ] LOW - If no results, then message appears.
- [ ] LOW the text for the beer that is appended to the page needs to be changed (ex. hoppiness and color both give a number instead of "very hoppy" and "dark") - NOT ASSIGNED SINCE LOW
- [ ] LOW code is confusing and messy atm - NOT ASSIGNED SINCE LOW
- [ ] LOW - hide "your recommended beers" until there are actually recommended beers to show ----> poss. solution: use jquery to create that div/header OR use jquery to append the text after user hits submit button

- [x] LOW -Materialize Progress Bar - Julie
- [x] MED - finalize splash page - Derek
- [x] LOW giphy link if user <21 DEREK
- [x] HIGH firebase - set up variables to push data - DEREK

index.html - ???
- [x] merge enter and submit button into one 

zipcode.js
- [x] user validation for zip code (5 digits, exists in the USA) 

brew.js
- [x] HIGH!!! - Create a new function startOver() that runs when the submit button is clicked. Needs to reset everything back to how it initially was - JULIE
- [x] MEDIUM - If only choosing one criteria, it should always be matched (ex. user chooses light beer + no pref about abv/ibu. close matches should not include very dark beer with random abv/ibu) ------> poss solution: if user only chooses 1 criteria, no need to check for close matches, only exact. JULIE wanted to look at this. 

- [x] HIGH!! - Under grabBeer: code is appending all the breweries that have beers but we need it to append only the breweries that have beers that meet the criteria - 
- [x] the a mount of beers that meet the criteria is definitely wrong...i did 'no preference' of all three criteria and the code only spit out one beer per brewery.

css styling
- [x] HIGH!!! - SASS (new library) DEREK
- [x] HIGH!!! - zip code: remove float right, remove up/down arrows in text box, change text color to black inside text box - SARAH
- [x] MEDIUM - align everything properly - SARAH
- [x] MEDIUM - buttons: spacing / padding between the buttons, consistency between sharp corners vs rounded corners SARAH
- [x] MEDIUM - brewery + beer listings - MEREDITH??
- [x] LOW - add text shadow to "Find a Local Brew" (pls) - SARAH??
- [x] LOW - consistency: center everything? or all to left? or mix? - SARAH
- [x] LOW - make the hops pic full width of background?
- [x] MEDIUM need button color to change when selecting criteria for beer

other
- [x] MEDIUM need to make the splash.html page show up first - JULIE
- [x] MEDIUM derek's text of stuff in the green div - DEREK

- [x] add pic to team (derek + julie) DEREK & JULIE
- [x] code runs slow (noticeable lag when waiting for the results to show up) ???
